version: '3'
services:
  db:
    container_name: ${MYSQL_NAME}
    image: mariadb
    ports:
        - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./docker-files/mysql:/var/lib/mysql"
  phpmyadmin:
    container_name: ${PHPMYADMIN_NAME}
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_USER: root 
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: db
    links:
      - db
  httpd:
    container_name: ${HTTPD_NAME}
    depends_on:
      - db
    image: custom-httpd-${HTTPD_NAME}
    links:
        - db
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - "./src:/var/www/html"
      - "./docker-files/bashrc_user:/home/application/.bashrc"
      - "./docker-files/bashrc_root:/root/.bashrc"
    environment:
      - WEB_DOCUMENT_ROOT="${HTTPD_DOCUMENT_ROOT}"
    build:
      context: ./docker-files
      dockerfile: Dockerfile
